/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** JS-side DeviceInfo. `sourceKind` is a string ("mic"|"system"|"process"). */
export interface JsDeviceInfo {
  id: string
  name: string
  sourceKind: string
  sampleRate: number
  channels: number
  isLoopback: boolean
  isDefault: boolean
}
/**
 * JS-side ProcessInfo (element of `processes()`). A candidate target for per-process capture.
 *
 * Passing `pid` to `openStream({ kind: 'process', processId: pid })` captures that process.
 * `name` / `executable` / `bundleId` are for display (they include values the app claims for
 * itself); the identity key is `pid`.
 */
export interface JsProcessInfo {
  /** OS process ID (non-zero). Pass it as `processId` to `openStream`. */
  pid: number
  /**
   * Display name (never empty). OS-reported name → executable name → bundle ID →
   * `"pid <N>"`.
   */
  name: string
  /** Base name of the executable (e.g. `firefox` / `chrome.exe`). Only when available. */
  executable?: string
  /** macOS bundle ID (e.g. `com.apple.Music`). Only when available on macOS. */
  bundleId?: string
  /**
   * Whether it is outputting audio right now. Only when the OS exposes it (Linux = node is
   * Running / Windows = session is Active / macOS = IsRunningOutput). `undefined` means
   * unknown.
   */
  isOutputActive?: boolean
}
/**
 * JS-side AudioChunk. `data` is interleaved f32 (len = frames * channels).
 * `seq` (u64) is a BigInt to avoid precision loss. `flags` is the ChunkFlags bits (u32).
 *
 * Delivery shape (0.3.0): the `onChunk` of `openStream(options, onChunk)` is called with
 * **one argument** (this primary chunk). The secondary-tap (`secondaryOutput`) chunk is not a
 * second argument; it arrives in this primary chunk's `secondary` property. Finalized VAD
 * events likewise have no separate callback; they ride on the `vadEvents` of the chunk of the
 * tap selected by `vadTap` (`chunk.vadEvents` for 'primary', `chunk.secondary?.vadEvents` for
 * 'secondary').
 *
 * `vadEvents` is filled only when `vad` is passed to `openStream`. With VAD disabled it is
 * unset (`undefined`). With VAD enabled it is an empty array when the chunk finalized no
 * events.
 */
export interface JsAudioChunk {
  data: Float32Array
  frames: number
  ptsNs: number
  seq: bigint
  flags: number
  droppedBefore: number
  peak: number
  rms: number
  /** VAD events finalized in this chunk (only when `vadTap` is 'primary'). */
  vadEvents?: Array<JsVadEvent>
  /**
   * The time-matched secondary-tap chunk (only when `secondaryOutput` is set). Delivered as
   * a pair in the same callback (`primary.secondary` of `onChunk(primary)`, not a second
   * argument). `undefined` on rounds where the secondary has not arrived yet. Match
   * primary↔secondary by `ptsNs` (time) (`seq` is independent per tap).
   */
  secondary?: JsSecondaryChunk
}
/**
 * JS-side secondary-tap chunk (only when `secondaryOutput` is set).
 *
 * `data` is the typed array matching `encoding` (`Int16Array` for `'s16'`, `Float32Array` for
 * `'f32'`). Sample values are in the host's native endianness. Serializing to the s16le wire
 * format is the receiver's (consumer's) responsibility. `ptsNs` is on the same
 * recording-start-zero clock as the primary, but its values are independent of the primary
 * and lag it by 20-60ms due to the group delay of the secondary Stage2 resampler.
 */
export interface JsSecondaryChunk {
  data: Int16Array | Float32Array
  /** 'f32' | 's16' (discriminant for narrowing the type of `data`). */
  encoding: string
  frames: number
  ptsNs: number
  seq: bigint
  flags: number
  droppedBefore: number
  /** Computed on the pre-quantization f32 (no loss of meter precision even for s16). */
  peak: number
  rms: number
  /** VAD events finalized in this chunk (only when `vadTap` is 'secondary'). */
  vadEvents?: Array<JsVadEvent>
}
/**
 * JS-side VAD event (start/end of a speech segment).
 *
 * `type` takes only the two values `'speechStart' | 'speechEnd'` (consistent with the `type`
 * of other events).
 *
 * `atSample` is an absolute sample position **in the VAD's internal rate (`sampleRate` = 8000
 * or 16000, default 16000)**, not in input-chunk samples (raw silero value; for standalone /
 * debug use). To convert to seconds use `atSample / sampleRate`; the input sample position can
 * be approximated as `atSample * inputSampleRate / sampleRate`.
 */
export interface JsVadEvent {
  /** 'speechStart' | 'speechEnd' (start/end of a speech segment). */
  type: 'speechStart' | 'speechEnd'
  atSample: number
  /**
   * Absolute nanoseconds from recording start (`number` = f64). Filled only via the
   * integrated VAD (`vad` of `openStream`) (computed from the chunk's `ptsNs` and the
   * in-chunk offset at the VAD internal rate). Delivered in the same chunk and monotonically
   * non-decreasing across chunks. The final events of `flushVad` ride on the same
   * `vadEvents` array. `undefined` for the standalone `Vad` class (`process`/`flush`), which
   * has no pts context. (Time is bounded by the recording length, hence `number`; only
   * `seq`, a raw u64 counter, is `bigint`.)
   */
  atNs?: number
}
/** JS-side native format (return value of `FlexStream.nativeFormat`). */
export interface JsNativeFormat {
  sampleRate: number
  channels: number
}
/**
 * Integrated VAD settings (shared by `OpenOptions.vad` and the `Vad` constructor).
 *
 * Every field is optional; omitted fields take the silero-compliant defaults
 * (`VadConfig::default`).
 */
export interface VadOptions {
  /** Probability threshold for treating it as speech start (>=). Default 0.5. */
  threshold?: number
  /**
   * Negative threshold for treating it as silence start (<). Defaults to
   * `max(threshold - 0.15, 0.01)`.
   */
  negThreshold?: number
  /** Minimum length of an accepted speech segment (ms). Default 250. */
  minSpeechMs?: number
  /** Silence length required to finalize speech end (ms). Default 100. */
  minSilenceMs?: number
  /** Padding that widens segment boundaries on both sides (ms). Default 30. */
  speechPadMs?: number
  /**
   * Maximum length of one segment (ms). 0 = unbounded. Force-split when exceeded.
   *
   * The standalone `Vad` class is silero-faithful with default 0 (unbounded). **The
   * integrated VAD (`vad` of `openStream`) defaults to 30000ms when omitted (bounding
   * monologues to keep real-time latency down)**. An explicit value (including `0`) wins.
   */
  maxSpeechMs?: number
  /** Internal sample rate of the VAD. Only 8000 or 16000. Default 16000. */
  sampleRate?: number
}
/** JS-side stream event. `type` is the kind; `count`/`message` are optional. */
export interface JsStreamEvent {
  type: string
  count?: number
  message?: string
}
/** JS-side device event. `type` is the kind; device/id/sourceKind are optional. */
export interface JsDeviceEvent {
  type: string
  device?: JsDeviceInfo
  id?: string
  sourceKind?: string
}
/**
 * Secondary output tap specification (`OpenOptions.secondaryOutput`).
 *
 * Returns the same capture as the primary output (`outputRate`/`outputChannels`) in a
 * different format at the same time. Used for paired capture such as 48k/stereo for storage
 * + 16k/mono/s16 for recognition.
 */
export interface SecondaryOutputOptions {
  /** Secondary output sample rate (Hz). E.g. 16000. */
  rate: number
  /** Secondary output channel count (1=mono / 2=stereo). E.g. 1. */
  channels: number
  /**
   * Sample encoding of secondary chunks. 'f32' (default) | 's16'. s16 is quantized after
   * the VAD and returned as an `Int16Array` (values in native endianness).
   */
  encoding?: string
}
/** Options for openStream / __openMockStream. */
export interface OpenOptions {
  /** "mic" | "system" | "process" | "mix" */
  kind: string
  deviceId?: string
  processId?: number
  /**
   * How the target PID of process is treated (process only). "include" (default) |
   * "exclude". include = capture only the target PID / exclude = all system audio except
   * the target PID (process_id required). Ignored for mic / system. Supported on all three
   * OSes: Linux / Windows / macOS.
   */
  mode?: string
  /**
   * Whether to exclude the host's own (own process) audio from system audio (system only;
   * for mix it applies to the system side). Default false. Ignored for mic / process.
   * Supported on all three OSes: Linux / Windows / macOS.
   */
  excludeSelf?: boolean
  /** Default 48000 */
  outputRate?: number
  /** Default 2 */
  outputChannels?: number
  /** Default 20 */
  chunkMs?: number
  /**
   * Initial input gain (linear factor). Default 1.0. 1.0 = unchanged, 2.0 = about +6dB,
   * 0.0 = silence. Change it at runtime with `setGain`.
   */
  gain?: number
  /** Input device ID selected for the mic side of mix (mix only). Default input if unset. */
  micDeviceId?: string
  /**
   * Output endpoint ID selected for the system side of mix (mix only). Default output if
   * unset.
   */
  systemDeviceId?: string
  /**
   * Pre-mix factor for the mic side of mix (linear, mix only). Default 1.0. `gain` is applied
   * after mixing.
   */
  micGain?: number
  /** Pre-mix factor for the system side of mix (linear, mix only). Default 1.0. */
  systemGain?: number
  /**
   * Integrated VAD settings. When set, the tap selected by `vadTap` is fed to the VAD and
   * finalized events are attached to that tap's chunk `vadEvents` (the audio itself is not
   * modified). VAD is disabled when omitted.
   */
  vad?: VadOptions
  /**
   * Tap the VAD runs on. 'primary' (default) | 'secondary'. 'secondary' is valid only when
   * `secondaryOutput` is set, and is efficient when the secondary is 16k/mono since
   * resampling is skipped.
   */
  vadTap?: string
  /**
   * true enables capture-time noise suppression. **Usable only when the output is 48000 Hz**
   * (RNNoise is fixed at 48kHz). When enabled it is applied once to the 48kHz/stereo
   * internal canonical form, and both the primary and secondary taps receive denoised audio
   * (+10ms fixed latency). Setting it to true with a rate other than 48kHz makes
   * `openStream` throw InvalidArg. Omitted/false means no noise suppression.
   */
  denoise?: boolean
  /**
   * Secondary output tap. When set, chunks in a different format are returned paired with
   * the primary at the same time (`primary.secondary` of `onChunk`). When omitted there is
   * no secondary tap = same as before.
   */
  secondaryOutput?: SecondaryOutputOptions
}
/**
 * Enumerates the available devices. In a headless environment it does not throw, even if
 * the array is empty.
 */
export declare function devices(): Array<JsDeviceInfo>
/**
 * Enumerates the processes that have an audio output session (stream) and can therefore be
 * targeted by per-process capture (`openStream({ kind: 'process', processId })`). The
 * calling process itself is not included. Stopped / Idle ones are listed too. Check
 * `isOutputActive` to see whether one is playing right now.
 *
 * Ordering is "outputting (`isOutputActive: true`) first → display name → pid", and entries
 * with the same pid are merged into one. Read-only; it shows no permission prompt. It
 * returns within at most 3 seconds even if the OS does not respond. It runs on the libuv
 * thread pool, so it does not block the JS event loop.
 *
 * - Linux (PipeWire): clients that have a `Stream/Output/Audio` node. `executable` is from
 *   `/proc/<pid>/exe`, or `/proc/<pid>/comm` if that cannot be read.
 * - Windows: processes that have an audio session on an active output device. Both
 *   enumeration and capture require Windows build 20348 or later (Windows 11 / Windows
 *   Server 2022).
 * - macOS 14.4+: process objects known to Core Audio (with `bundleId`; input-only processes
 *   are included too).
 *
 * How to read the result: an empty array = per-process capture is available but no such
 * process exists right now (not "nothing is playing"). A rejection = per-process capture is
 * unavailable in this environment (PipeWire unreachable on Linux; `unsupported OS version`
 * below macOS 14.4 / Windows build 20348; `unsupported` on other OSes; permission denied),
 * the OS did not respond in time, or the previous query has not finished yet (same `Error`
 * type and wording as in the synchronous era).
 */
export declare function processes(): Promise<Array<JsProcessInfo>>
/**
 * Opens and starts a stream and returns a `FlexStream` that sends chunks/events to the
 * callbacks.
 *
 * Setting `options.denoise` enables noise suppression in core (internal canonical form), and
 * both the primary and secondary taps receive denoised audio. Setting `options.vad` feeds the
 * tap selected by `vadTap` to the VAD and attaches finalized events to that tap's chunk
 * `vadEvents` (with `atNs`, the absolute time from recording start). Setting
 * `options.secondaryOutput` enables the secondary tap, which returns chunks in a different
 * format paired with the primary (`primary.secondary` of `onChunk`). The denoise 48kHz
 * precondition and invalid VAD settings are validated and rejected here, before the stream
 * is opened.
 *
 * Standard operation enables the secondary tap and VAD for the entire
 * recording. Toggle transcription by keeping or discarding the delivered
 * results, not by re-opening the stream; the secondary format is fixed at open
 * (see `switchSource`), so the recognition resample + VAD run on every
 * recording — budget for them as a constant cost, not an opt-in. The integrated
 * VAD defaults `maxSpeechMs` to 30 s (see `VadOptions`) so a monologue with no
 * silence stays bounded; call `flushVad` to force-close the open utterance
 * (e.g. when pausing recognition). Per-chunk `vadEvents[].atNs` is a recording
 * zero-based absolute time that is monotonic non-decreasing across chunks.
 *
 * `onChunk` is called with **one** argument, the primary `JsAudioChunk`. When
 * `secondaryOutput` is set, the paired secondary chunk arrives as
 * `chunk.secondary` (it is not a second callback argument). VAD results ride
 * on the chunk of the tap selected by `vadTap`: `chunk.vadEvents` for
 * 'primary', `chunk.secondary?.vadEvents` for 'secondary'. Do not block
 * synchronously inside `onChunk` (defer heavy work to a later task); blocking
 * stalls terminator delivery and delays `stop()` resolving.
 */
export declare function openStream(options: OpenOptions, onChunk: (chunk: JsAudioChunk) => void, onEvent?: ((event: JsStreamEvent) => void) | undefined | null): FlexStream
/**
 * Watches device hotplug and returns a `DeviceWatcherHandle` that sends events to the
 * callback.
 */
export declare function watchDevices(onEvent: (event: JsDeviceEvent) => void): DeviceWatcherHandle
/**
 * Test-only; not part of the public API.
 *
 * Creates a stream by passing a `MockBackend` to the low-level `Stream::open` and runs it
 * through the same bridge / TSFN path as `open_stream`. Verifies the whole marshaling path
 * (Float32Array, BigInt, peak/rms, frames) end-to-end without real audio. Do not use it from
 * production code.
 *
 * Passing `secondaryRate` enables the secondary tap (`secondaryChannels` = default 1,
 * `secondaryEncoding` = 'f32'|'s16', default 'f32'), so pairing, s16 quantization, and
 * `Int16Array` marshalling can be verified without real audio (no real capture needed).
 *
 * Passing `vadThreshold` enables the integrated VAD (`vadTap` = 'primary'|'secondary',
 * default 'primary'), so `flushVad`, the `atNs` of `vadEvents`, and the automatic flush of
 * `stop()` can be verified without real audio. For testing it is built with
 * `minSpeechMs=0`, so with threshold 0 `flushVad` reliably finalizes the open speech segment
 * (real-time end-of-recording finalization can be verified even with a synthetic wave that
 * never goes silent).
 *
 * The JS name is `__openMockStream`. The leading `__` marks it as outside the public API.
 * napi's default conversion would drop the leading underscores and turn it into
 * `openMockStream`, so it is pinned with `js_name`.
 */
export declare function __openMockStream(sampleRate: number, channels: number, freqHz: number, onChunk: (chunk: JsAudioChunk) => void, secondaryRate?: number | undefined | null, secondaryChannels?: number | undefined | null, secondaryEncoding?: string | undefined | null, vadThreshold?: number | undefined | null, vadTap?: string | undefined | null): FlexStream
/**
 * Handle to a capture stream. Internally a bridge thread owns and polls the
 * `flexaudio::Stream` and sends chunks/events to JS via TSFNs.
 */
export declare class FlexStream {
  /**
   * Stops the capture. By the time the Promise resolves, every `onChunk` queued on the TSFN
   * before the stop (the last PCM and the `frames:0` terminator) has been handed to JS.
   * A second call waits for the same completion / resolves immediately if already done.
   * Calling it from inside `onChunk` does not hang, because there is no join on the JS
   * thread.
   */
  stop(): Promise<void>
  /**
   * Hot-swaps the input source (mic/system/process) without stopping the capture.
   *
   * Asks the bridge thread to switch to the `StreamConfig` built from `options` and returns
   * the result synchronously (`Ok` on success, an exception on failure). The output format
   * (`outputRate`/`outputChannels`) cannot be changed by a switch (it would change the
   * frames of the continuous stream). Requesting a change makes `switch_source` return
   * InvalidArg, which becomes an exception here. The chunk `seq` is continuous across the
   * switch, and the first chunk after the switch has the DISCONTINUITY flag set.
   * `options.gain` is ignored (gain is stream state; change it with `setGain`).
   *
   * Throws if already `stop()`ped (after the bridge thread has stopped).
   */
  switchSource(options: OpenOptions): void
  /**
   * Pauses the capture. The device keeps running; only delivery stops. Resume with
   * `resume`; the first chunk after resuming has DISCONTINUITY set. Throws if already
   * `stop()`ped.
   */
  pause(): void
  /** Clears the pause and resumes delivery. Throws if already `stop()`ped. */
  resume(): void
  /**
   * Force-finalizes the integrated VAD's "currently open speech segment" (runtime
   * operation).
   *
   * silero emits no `speechEnd` until silence arrives, so call this when pausing
   * recognition or when you want to finalize the last speech segment at the end of a
   * recording. If a speech segment is open, the final `speechEnd` (and its paired
   * `speechStart`) ride at the front of the `vadEvents` (with `atNs` from recording start)
   * of the next chunk arriving on the tap (a chunk flows every 20ms, so the delay is ≤ 1
   * chunk). After the call the VAD is reset, and the next speech is picked up in a fresh
   * context.
   *
   * This **does not change the config** (unrelated to `secondaryOutput`/encoding being
   * fixed at open = not changeable by `switchSource`). It is also distinct from the audio
   * stop-flush and does not modify audio samples. Does nothing if no VAD is configured.
   * `stop()` runs this automatically after the audio stop-flush. Throws if already
   * `stop()`ped.
   */
  flushVad(): void
  /**
   * Changes the input gain (linear factor). 1.0 = unchanged, 2.0 = about +6dB, 0.0 =
   * silence. Can be called at any time during capture and takes effect from the next chunk
   * (20ms granularity). Samples after multiplication are clamped to ±1.0. Throws unless it
   * is finite and >= 0. Throws if already `stop()`ped.
   */
  setGain(gain: number): void
  /** Whether it is currently paused. Throws if already `stop()`ped. */
  isPaused(): boolean
  /** Current input gain (linear factor). Throws if already `stop()`ped. */
  gain(): number
  /**
   * Native format `{ sampleRate, channels }` of the current backend. For display and
   * diagnostics (the chunks actually delivered use the output format
   * `outputRate`/`outputChannels`). Changing the source with `switchSource` updates it to
   * the new backend's values. Throws if already `stop()`ped.
   */
  nativeFormat(): JsNativeFormat
  /**
   * Cumulative number of chunks the chunk ring discarded with DROP_OLDEST (BigInt). Throws
   * if already `stop()`ped.
   */
  droppedChunks(): bigint
}
/** Handle to the device hotplug watch. A bridge thread polls the `DeviceWatcher`. */
export declare class DeviceWatcherHandle {
  /** Stops the watch and joins the bridge thread. Safe to call twice. */
  stop(): void
}
/**
 * Handle to an offline VAD (silero-VAD on ONNX, model embedded).
 *
 * One instance holds one ONNX session. Feeding any format (interleaved f32 at
 * `inputSampleRate` / `inputChannels`) to [`Vad::process`] converts it internally to mono at
 * the VAD rate, detects speech segments, and returns the finalized [`JsVadEvent`]s. Use it
 * when you want to classify an arbitrary sample sequence yourself instead of using the
 * integrated VAD of `openStream`.
 */
export declare class Vad {
  /**
   * Builds a VAD from an options object (loads the embedded model). InvalidArg if the
   * settings are invalid (sampleRate other than 8000/16000, threshold outside `[0,1]`,
   * etc.); GenericFailure if the model fails to load.
   */
  constructor(options: VadOptions)
  /**
   * Processes interleaved f32 in any format and returns the finalized [`JsVadEvent`]s.
   *
   * Partial frames are carried over internally, so the input may be split at any position.
   * `atSample` is in the VAD internal rate (see [`JsVadEvent`]).
   */
  process(samples: Float32Array, inputSampleRate: number, inputChannels: number): Array<JsVadEvent>
  /**
   * Force-finalizes the currently open speech segment and returns the finalized
   * [`JsVadEvent`]s (same behavior as reaching the end of input). After the call the
   * internal state is reset, and the next `process` starts from a fresh context. No model
   * inference runs, so it is lightweight and deterministic.
   *
   * The standalone `Vad` has no pts context, so `atNs` is `undefined` (`atSample` is the raw
   * cumulative position at the VAD internal rate). Returns an empty array when no speech is
   * in progress.
   */
  flush(): Array<JsVadEvent>
  /**
   * Initializes the internal state (state / context / state machine / sample position /
   * resampler).
   */
  reset(): void
}
/**
 * Writer that incrementally saves capture chunks losslessly to FLAC files.
 *
 * With `splitSeconds` of 1 or more, each time the number of written frames reaches
 * `splitSeconds × sampleRate` the current file is closed and it rotates to the next file with
 * a 3-digit sequence number, `name-001.flac, name-002.flac, …` (same convention as the CLI's
 * WAV splitting). The boundary is "move on once reached or exceeded" at chunk granularity, so
 * each file can be up to one chunk longer than the specified seconds, but chunks are never
 * split and nothing is dropped. With `splitSeconds` omitted/0 it is a single file.
 */
export declare class FlacEncoder {
  /**
   * Creates a FLAC writer. `splitSeconds` omitted/0 gives a single file; 1 or more rotates
   * by seconds.
   *
   * `channels` is 1..=2, `sampleRate` is 1..=96000 Hz (InvalidArg when out of range). When
   * splitting, the first file (`name-001.flac`) is created immediately.
   */
  static create(path: string, sampleRate: number, channels: number, splitSeconds?: number | undefined | null): FlacEncoder
  /**
   * Appends interleaved f32 (length a multiple of `channels`). InvalidArg if it is not a
   * multiple.
   *
   * After writing, if the current file's frame count is at or above the threshold, it is
   * finalized immediately and rotation moves to the next file (the next `writeChunk` becomes
   * the start of the new file).
   */
  writeChunk(samples: Float32Array): void
  /**
   * Writes out the remainder, finalizes the header, and closes the open file. Safe to call
   * twice (the second and later calls are no-ops). Discarding it without calling this still
   * closes the file best-effort via `FlacWriter`'s Drop, but call this if you want to detect
   * write errors.
   */
  finalize(): void
}
/**
 * Offline noise suppressor (RNNoise via nnnoiseless, weights embedded). **Assumes 48kHz**
 * and is intended to reduce stationary noise in microphone recordings (fans, air
 * conditioning, typing, etc.).
 *
 * It has a fixed latency of [`FRAME_SIZE`](flexaudio_denoise::FRAME_SIZE) (10ms at 48kHz);
 * the output is the input delayed by one frame. The first frame of the stream is silent
 * padding, and the one frame left at the end is retrieved with [`Denoiser::flush`].
 */
export declare class Denoiser {
  /**
   * Builds it for the given channel count (1 = mono, 2 = stereo interleaved). InvalidArg
   * when out of range.
   */
  constructor(channels: number)
  /**
   * Noise-suppresses interleaved f32 of any length (normalized to ±1.0, 48kHz, length a
   * multiple of channels) and returns it as a **new array** (a copy, since in-place is
   * awkward in napi). InvalidArg if the length is not a multiple of channels.
   */
  process(samples: Float32Array): Float32Array
  /**
   * Processes the carried-over remainder, returns the trailing delayed portion (1
   * frame/ch), and closes the stream. After the call it is back in the freshly-created
   * state and can go on to process another stream.
   */
  flush(): Float32Array
  /** Initializes the RNN state, the carry-over, and the delay line. */
  reset(): void
}
