/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** JS DeviceInfo. `sourceKind` is a string ("mic"|"system"|"process"). */
export interface JsDeviceInfo {
  id: string
  name: string
  sourceKind: string
  sampleRate: number
  channels: number
  isLoopback: boolean
  isDefault: boolean
}
/**
 * JS ProcessInfo (an element of `processes()`). A candidate for per-process capture.
 *
 * Pass `pid` to `openStream({ kind: 'process', processId: pid })` to record that process.
 * `name` / `executable` / `bundleId` are for display (including self-reported app values);
 * the identity key is `pid`.
 */
export interface JsProcessInfo {
  /** OS process ID (nonzero). Pass to `openStream` as `processId`. */
  pid: number
  /** Display name (always nonempty). OS-reported name → executable name → bundle ID → `"pid <N>"`. */
  name: string
  /** Executable basename (e.g. `firefox` / `chrome.exe`). Present only when available. */
  executable?: string
  /** macOS bundle ID (e.g. `com.apple.Music`). Present only when available on macOS. */
  bundleId?: string
  /**
   * Whether audio is currently playing. Only when exposed by the OS (Linux=node Running /
   * Windows=session Active / macOS=IsRunningOutput). `undefined` means unknown.
   */
  isOutputActive?: boolean
}
/**
 * JS AudioChunk. `data` is interleaved f32 (len = frames * channels).
 * `seq` (u64) uses BigInt to avoid precision loss. `flags` contains ChunkFlags bits (u32).
 *
 * Delivery shape (0.3.0): `onChunk` in `openStream(options, onChunk)` receives **one argument**
 * (this primary chunk). Secondary tap (`secondaryOutput`) chunks arrive in the primary chunk's
 * `secondary` property, rather than a second argument. Finalized VAD events also arrive on
 * the selected `vadTap` chunk's `vadEvents`, rather than a separate callback
 * ('primary': `chunk.vadEvents`; 'secondary': `chunk.secondary?.vadEvents`).
 *
 * `vadEvents` is populated only when `vad` is specified in `openStream`. When VAD is disabled,
 * it is unset (`undefined`). When enabled with no finalized events in this chunk, it is an empty array.
 */
export interface JsAudioChunk {
  data: Float32Array
  frames: number
  ptsNs: number
  seq: bigint
  flags: number
  droppedBefore: number
  peak: number
  rms: number
  /** VAD events finalized in this chunk (only when `vadTap` is 'primary'). */
  vadEvents?: Array<JsVadEvent>
  /**
   * Timestamp-matched secondary tap chunk (only with `secondaryOutput`). Delivered as a pair in
   * the same callback (`primary.secondary` in `onChunk(primary)`, not a second argument). It is
   * `undefined` when the secondary has not arrived. Match primary↔secondary by `ptsNs` (time);
   * `seq` is independent for each tap.
   */
  secondary?: JsSecondaryChunk
}
/**
 * JS secondary tap chunk (only with `secondaryOutput`).
 *
 * `data` is a typed array matching `encoding` (`Int16Array` for `'s16'`,
 * `Float32Array` for `'f32'`). Sample values use host native endianness. Serialization to s16le
 * wire format is the receiver's (consumer's) responsibility. `ptsNs` uses the same recording-zero
 * clock as the primary but is independent, trailing by 20–60ms due to secondary Stage2 resampler group delay.
 */
export interface JsSecondaryChunk {
  data: Int16Array | Float32Array
  /** 'f32' | 's16' (discriminator for narrowing the type of `data`). */
  encoding: string
  frames: number
  ptsNs: number
  seq: bigint
  flags: number
  droppedBefore: number
  /** Computed from f32 before quantization (preserves meter precision even with s16). */
  peak: number
  rms: number
  /** VAD events finalized in this chunk (only when `vadTap` is 'secondary'). */
  vadEvents?: Array<JsVadEvent>
}
/**
 * JS VAD event (speech segment start/end).
 *
 * `type` is limited to `'speechStart' | 'speechEnd'` (consistent with other events' `type`).
 *
 * `atSample` is an absolute sample position **at VAD's internal rate (`sampleRate`=8000 or 16000,
 * default 16000)**, not the input chunk's sample rate (raw silero value for standalone/debug use).
 * Convert to seconds with `atSample / sampleRate`; approximate the input sample position with
 * `atSample * inputSampleRate / sampleRate`.
 */
export interface JsVadEvent {
  /** 'speechStart' | 'speechEnd' (speech segment start/end). */
  type: 'speechStart' | 'speechEnd'
  atSample: number
  /**
   * Absolute nanoseconds from recording zero (`number`=f64). Populated only through integrated VAD
   * (`vad` in `openStream`), computed from chunk `ptsNs` and the within-chunk offset at VAD's
   * internal rate. Delivered in the same chunk and monotonic non-decreasing across chunks. Final
   * `flushVad` events use the same `vadEvents` array. Standalone `Vad` (`process`/`flush`) has no pts
   * context, so this is `undefined`. (Time is bounded by recording length: `number`; only raw u64 `seq` uses `bigint`.)
   */
  atNs?: number
}
/** JS native format (returned by `FlexStream.nativeFormat`). */
export interface JsNativeFormat {
  sampleRate: number
  channels: number
}
/**
 * Integrated VAD settings (shared by `OpenOptions.vad` and the `Vad` constructor).
 *
 * All fields are optional; omitted fields use silero defaults (`VadConfig::default`).
 */
export interface VadOptions {
  /** Probability threshold for speech start (>=). Default 0.5. */
  threshold?: number
  /** Lower (silence-side) threshold for silence start (<). Defaults to `max(threshold - 0.15, 0.01)`. */
  negThreshold?: number
  /** Minimum accepted speech duration (ms). Default 250. */
  minSpeechMs?: number
  /** Silence duration required to finalize speech end (ms). Default 100. */
  minSilenceMs?: number
  /** Padding extending segment boundaries on both sides (ms). Default 30. */
  speechPadMs?: number
  /**
   * Maximum segment length (ms). 0 = unbounded. Exceeding this forces a split.
   *
   * Standalone `Vad` follows silero with default 0 (unbounded). **Integrated VAD (`vad` in `openStream`)
   * defaults to 30000ms (caps long stretches of speech so realtime latency stays bounded)**.
   * An explicit value (including `0`) always wins.
   */
  maxSpeechMs?: number
  /** VAD internal sample rate. Only 8000 or 16000. Default 16000. */
  sampleRate?: number
}
/**
 * Stream notification. permissionDenied is terminal, with permission and
 * actionable message. silenceWhileSourceActive is advisory: capture continues;
 * missing system-audio permission and genuine digital silence are both possible.
 */
export interface JsStreamEvent {
  /** Present on permissionDenied. */
  permission?: 'microphone' | 'systemAudio'
  type: string
  count?: number
  message?: string
}
/** JS device event. `type` identifies the kind; device/id/sourceKind are optional. */
export interface JsDeviceEvent {
  type: string
  device?: JsDeviceInfo
  id?: string
  sourceKind?: string
}
/**
 * Secondary output tap specification (`OpenOptions.secondaryOutput`).
 *
 * Returns the same capture as the primary output (`outputRate`/`outputChannels`) in another format simultaneously.
 * Used for paired outputs such as 48k/stereo storage + 16k/mono/s16 recognition.
 */
export interface SecondaryOutputOptions {
  /** Secondary output sample rate (Hz). Example: 16000. */
  rate: number
  /** Secondary output channel count (1=mono / 2=stereo). Example: 1. */
  channels: number
  /**
   * Secondary chunk sample encoding. 'f32' (default) | 's16'. s16 is quantized after VAD
   * and returned as `Int16Array` (native-endian values).
   */
  encoding?: string
}
/** Options for openStream / __openMockStream. */
export interface OpenOptions {
  /** "mic" | "system" | "process" | "mix" */
  kind: string
  deviceId?: string
  /**
   * Target process ID for `process` capture. Must be a finite positive integer
   * in 1..=4294967295; invalid values fail with InvalidArg.
   */
  processId?: number
  /**
   * How to handle the target PID for process capture (process only). "include" (default) | "exclude".
   * include=record only the target PID / exclude=all system audio except the target PID (process_id required).
   * Ignored for mic / system. Supported on all three OSes: Linux / Windows / macOS.
   */
  mode?: string
  /**
   * Exclude the host process from `system` capture (also the system side of
   * `mix`). Defaults to false; ignored by mic/process. Supported on Linux,
   * Windows and macOS. Windows excludes the host's entire process tree;
   * Electron's audio utility process is a direct child and is covered.
   */
  excludeSelf?: boolean
  /**
   * Process IDs whose playback is excluded from `system` capture (also the
   * system side of `mix`), in addition to `excludeSelf`. Each must be a finite
   * positive integer in 1..=4294967295; invalid values fail with InvalidArg.
   * On macOS, each PID must also fit a positive signed 32-bit integer
   * (1..=2147483647), or capture fails.
   * Duplicates are allowed. Ignored by mic/process after validation.
   * Linux and macOS exclude every listed PID. macOS resolves audio objects
   * at capture start: a PID without one is not excluded; a failed lookup
   * fails the open unless the process is gone.
   * On Linux, while exclusion is active, a pipewire-pulse-relayed stream
   * without a known application.process.id is not captured.
   * Windows can exclude only one process tree. For Electron, use
   * `excludeSelf: true` alone; any other PID fails with an error.
   */
  excludePids?: Array<number>
  /** Default 48000 */
  outputRate?: number
  /** Default 2 */
  outputChannels?: number
  /** Default 20 */
  chunkMs?: number
  /**
   * Initial input gain (linear multiplier). Default 1.0. 1.0=unchanged, 2.0=about +6dB, 0.0=silence.
   * Use `setGain` for runtime changes.
   */
  gain?: number
  /** Input device ID for the mic side of mix (mix only). Defaults to the default input. */
  micDeviceId?: string
  /** Output endpoint ID for the system side of mix (mix only). Defaults to the default output. */
  systemDeviceId?: string
  /** Pre-mix multiplier for the mic side (linear, mix only). Default 1.0. `gain` applies after mixing. */
  micGain?: number
  /** Pre-mix multiplier for the system side (linear, mix only). Default 1.0. */
  systemGain?: number
  /**
   * Integrated VAD settings. When specified, the tap selected by `vadTap` passes through VAD and
   * finalized events attach to that tap's chunk `vadEvents` (audio is unchanged). Omission disables VAD.
   */
  vad?: VadOptions
  /**
   * Tap to run VAD on. 'primary' (default) | 'secondary'. 'secondary' requires
   * `secondaryOutput`; a 16k/mono secondary avoids resampling for efficiency.
   */
  vadTap?: string
  /**
   * true enables recording-time noise suppression. **Only available with 48000 Hz output**
   * (RNNoise is fixed at 48kHz). Applied once to the internal 48kHz/stereo canonical form;
   * both primary and secondary taps receive denoised audio (+10ms fixed latency). Setting true
   * at any other rate makes `openStream` throw InvalidArg. Omission/false disables noise suppression.
   */
  denoise?: boolean
  /**
   * Secondary output tap. When specified, returns paired chunks in another format simultaneously
   * (`primary.secondary` in `onChunk`). Omission means no secondary tap, preserving previous behavior.
   */
  secondaryOutput?: SecondaryOutputOptions
}
/** Enumerate available devices. An empty array in a headless environment does not throw. */
export declare function devices(): Array<JsDeviceInfo>
/**
 * Enumerate processes with audio output sessions (streams) that can be targeted by per-process
 * capture (`openStream({ kind: 'process', processId })`). Excludes the calling process itself.
 * Stopped/Idle sessions are included. Use `isOutputActive` to check whether audio is playing.
 *
 * Sorted by active output (`isOutputActive: true`) first → display name → pid, with each pid
 * deduplicated. Read-only, with no permission prompts. Returns within 3 seconds even if the OS
 * does not respond. Runs on the libuv thread pool without blocking the JS event loop.
 *
 * - Linux (PipeWire): clients with `Stream/Output/Audio` nodes. `executable` comes from
 *   `/proc/<pid>/exe`, falling back to `/proc/<pid>/comm` if unreadable.
 * - Windows: processes with audio sessions on enabled output devices. Both enumeration and capture
 *   require Windows build 20348 or later (Windows 11 / Windows Server 2022).
 * - macOS 14.4+: process objects known to Core Audio (with `bundleId`,
 *   including input-only processes).
 *
 * Interpreting results: an empty array means per-process capture is available but no qualifying
 * processes currently exist (not "nothing is playing"). Rejection means per-process capture is
 * unavailable (PipeWire unreachable on Linux; macOS below 14.4 / Windows below build 20348 return
 * `unsupported OS version`; other OSes return `unsupported`; permission denied), the OS did not
 * respond within the time limit, or the previous query is still pending (same `Error`
 * type and wording as the synchronous version).
 */
export declare function processes(): Promise<Array<JsProcessInfo>>
/**
 * Open and start a stream, returning a `FlexStream` that sends chunks/events to callbacks.
 * Confirmed microphone/system-audio denial throws actionable permission guidance.
 * Supply onEvent for runtime denial and silenceWhileSourceActive advisories;
 * without onEvent, inspect terminalError() and handle stop() rejection.
 * macOS bundled microphone prompts wait up to 30 s; bare-host opens rely on the
 * responsible-app prompt and check late denial for up to 60 s. Windows checks
 * Microphone privacy, including Let desktop apps access your microphone.
 *
 * `options.denoise` enables noise suppression in core (internal canonical form), so both primary
 * and secondary taps receive denoised audio. `options.vad` runs VAD on the tap selected by `vadTap`
 * and attaches finalized events to that tap's chunk `vadEvents` (with absolute `atNs` from
 * recording zero). `options.secondaryOutput` enables the secondary tap, returning paired chunks
 * in another format (`primary.secondary` in `onChunk`). The denoise 48kHz requirement and
 * invalid VAD settings are checked and rejected here before opening the stream.
 *
 * Standard operation enables the secondary tap and VAD for the entire
 * recording. Toggle transcription by keeping or discarding the delivered
 * results, not by re-opening the stream; the secondary format is fixed at open
 * (see `switchSource`), so the recognition resample + VAD run on every
 * recording — budget for them as a constant cost, not an opt-in. The integrated
 * VAD defaults `maxSpeechMs` to 30 s (see `VadOptions`) so a monologue with no
 * silence stays bounded; call `flushVad` to force-close the open utterance
 * (e.g. when pausing recognition). Per-chunk `vadEvents[].atNs` is a recording
 * zero-based absolute time that is monotonic non-decreasing across chunks.
 *
 * `onChunk` is called with **one** argument, the primary `JsAudioChunk`. When
 * `secondaryOutput` is set, the paired secondary chunk arrives as
 * `chunk.secondary` (it is not a second callback argument). VAD results ride
 * on the chunk of the tap selected by `vadTap`: `chunk.vadEvents` for
 * 'primary', `chunk.secondary?.vadEvents` for 'secondary'. Do not block
 * synchronously inside `onChunk` (defer heavy work to a later task); blocking
 * stalls terminator delivery and delays `stop()` resolving.
 */
export declare function openStream(options: OpenOptions, onChunk: (chunk: JsAudioChunk) => void, onEvent?: ((event: JsStreamEvent) => void) | undefined | null): FlexStream
/** Watch device attachment/removal and return a `DeviceWatcherHandle` that sends events to the callback. */
export declare function watchDevices(onEvent: (event: JsDeviceEvent) => void): DeviceWatcherHandle
/**
 * Test-only; outside the public API.
 *
 * Create a stream by passing `MockBackend` to low-level `Stream::open`, then run it through the
 * same bridge / TSFN path as `open_stream`. End-to-end verification of all marshaling paths
 * (Float32Array, BigInt, peak/rms, frames) without real audio. Do not use in production code.
 *
 * Passing `secondaryRate` enables the secondary tap (`secondaryChannels` defaults to 1;
 * `secondaryEncoding` is 'f32'|'s16', default 'f32'), allowing pairing, s16 quantization, and
 * `Int16Array` marshaling to be verified without real audio (no actual capture needed).
 *
 * Passing `vadThreshold` enables integrated VAD (`vadTap` is 'primary'|'secondary', default
 * 'primary'), allowing `flushVad`, `vadEvents` `atNs`, and automatic `stop()` flush to be verified
 * without real audio. Tests construct it with `minSpeechMs=0`, so threshold 0 lets `flushVad`
 * reliably finalize open utterances (verifies RT finalization even with synthetic waves lacking silence).
 *
 * JS name is `__openMockStream`. Leading `__` marks it outside the public API. napi's default
 * conversion drops leading underscores, producing `openMockStream`, so `js_name` fixes the name.
 */
export declare function __openMockStream(sampleRate: number, channels: number, freqHz: number, onChunk: (chunk: JsAudioChunk) => void, secondaryRate?: number | undefined | null, secondaryChannels?: number | undefined | null, secondaryEncoding?: string | undefined | null, vadThreshold?: number | undefined | null, vadTap?: string | undefined | null): FlexStream
/**
 * Recording stream handle. Internally, the bridge thread owns and polls `flexaudio::Stream`
 * and sends chunks/events to JS through TSFN.
 */
export declare class FlexStream {
  /**
   * Stop recording. When the Promise resolves, all `onChunk` calls queued on the TSFN before
   * stop (the last PCM and `frames:0` terminator) have been delivered to JS.
   * Repeated calls await the same completion, or resolve immediately if already complete. Calling
   * inside `onChunk` does not freeze JS because joining happens off the JS thread.
   * Rejects with actionable permission guidance on terminal denial; further audio
   * and the terminator are suppressed. Create a new stream after fixing permission.
   */
  stop(): Promise<void>
  /** Stored terminal failure, including after stop; does not consume onEvent. */
  terminalError(): JsStreamEvent | undefined
  /**
   * Hot-swap the input source (mic/system/process) without stopping recording.
   *
   * Request a switch to the `StreamConfig` built from `options` on the bridge thread and return
   * the result synchronously (`Ok` on success, exception on failure). The output format (`outputRate`/
   * `outputChannels`) cannot change during a switch (it would change frames in a continuous stream).
   * Requesting a change makes `switch_source` return InvalidArg, thrown here as an exception. Chunk
   * `seq` stays continuous across switches; the first chunk afterward has the DISCONTINUITY flag.
   * `options.gain` is ignored (gain is stream state; use `setGain` to change it).
   *
   * Throws if `stop()` has already completed (the bridge thread has stopped).
   */
  switchSource(options: OpenOptions): void
  /**
   * Pause recording. Keep the device running but stop delivery. `resume` restarts delivery;
   * the first chunk afterward has DISCONTINUITY. Throws if `stop()` has already completed.
   */
  pause(): void
  /** Unpause delivery. Throws the stored error on terminal failure. */
  resume(): void
  /**
   * Force-finalize integrated VAD's currently open utterance (runtime operation).
   *
   * silero emits no `speechEnd` until silence arrives. Call this when pausing recognition or
   * finalizing the last utterance at recording end. If an utterance is open, its final `speechEnd`
   * (and paired `speechStart`) are prepended to `vadEvents` of the next tap chunk (with `atNs`
   * from recording zero). Chunks arrive every 20ms, so latency is ≤ 1 chunk. VAD then
   * resets and detects the next utterance with fresh context.
   *
   * This **does not change config** (independent of `secondaryOutput`/encoding being fixed at open
   * and unchangeable through `switchSource`). It is also separate from audio stop-flush and does not
   * modify audio samples. No-op if VAD is not configured. `stop()` calls this automatically after audio
   * stop-flush. Throws if `stop()` has already completed.
   */
  flushVad(): void
  /**
   * Change input gain (linear multiplier). 1.0=unchanged, 2.0=about +6dB, 0.0=silence. Callable
   * any time during recording; takes effect on the next chunk (20ms granularity). Multiplied samples
   * are clamped to ±1.0. Throws unless finite and nonnegative, or if `stop()` has already completed.
   */
  setGain(gain: number): void
  /** Whether currently paused. Throws if `stop()` has already completed. */
  isPaused(): boolean
  /** Current input gain (linear multiplier). Throws if `stop()` has already completed. */
  gain(): number
  /**
   * Current backend's native format `{ sampleRate, channels }`, for display/diagnostics
   * (delivered chunks use output format `outputRate`/`outputChannels`).
   * Changing sources with `switchSource` updates this to the new backend's values. Throws if `stop()`
   * has already completed.
   */
  nativeFormat(): JsNativeFormat
  /**
   * Cumulative chunks discarded by the chunk ring's DROP_OLDEST policy (BigInt). Throws if `stop()`
   * has already completed.
   */
  droppedChunks(): bigint
}
/** Device attachment/removal watcher handle. The bridge thread polls `DeviceWatcher`. */
export declare class DeviceWatcherHandle {
  /** Stop watching and join the bridge thread. Safe to call repeatedly. */
  stop(): void
}
/**
 * Offline VAD handle (silero-VAD on ONNX, embedded model).
 *
 * Each instance owns one ONNX session. Feed arbitrary-format interleaved f32 (`inputSampleRate` /
 * `inputChannels`) to [`Vad::process`]; it converts to mono at the VAD rate internally,
 * detects speech segments, and returns finalized [`JsVadEvent`] values. Use this to classify arbitrary
 * sample sequences yourself instead of using integrated VAD in `openStream`.
 */
export declare class Vad {
  /**
   * Construct VAD from a settings object (load the embedded model). Invalid settings
   * (sampleRate other than 8000/16000, threshold outside `[0,1]`, etc.) yield InvalidArg;
   * model loading failure yields GenericFailure.
   */
  constructor(options: VadOptions)
  /**
   * Process arbitrary-format interleaved f32 and return finalized [`JsVadEvent`] values.
   *
   * Partial frames carry over internally, so input can be split anywhere. `atSample` uses
   * VAD's internal rate (see [`JsVadEvent`]).
   */
  process(samples: Float32Array, inputSampleRate: number, inputChannels: number): Array<JsVadEvent>
  /**
   * Force-finalize the currently open utterance and return finalized [`JsVadEvent`] values (same behavior
   * as reaching input end). Internal state then resets; the next `process` starts with fresh
   * context. No model inference runs, making this lightweight and deterministic.
   *
   * Standalone `Vad` has no pts context, so `atNs` is `undefined` (`atSample` remains the raw cumulative
   * position at VAD's internal rate). Returns an empty array when no utterance is open.
   */
  flush(): Array<JsVadEvent>
  /** Initialize internal state (state / context / state machine / sample position / resampler). */
  reset(): void
}
/**
 * Writer that incrementally saves recording chunks to FLAC files with lossless compression.
 *
 * When `splitSeconds` is at least 1, reaching `splitSeconds × sampleRate` written frames closes
 * the current file and rotates to the next, using three-digit sequence numbers such as
 * `name-001.flac, name-002.flac, …` (same convention as CLI WAV splitting). Boundaries advance
 * at chunk granularity when the threshold is reached, so each file may exceed the specified duration
 * by up to one chunk; chunks are never split and no data is dropped. Omitted/0 `splitSeconds` uses one file.
 */
export declare class FlacEncoder {
  /**
   * Create a FLAC writer. Omitted/0 `splitSeconds` uses one file; at least 1 enables timed rotation.
   *
   * `channels` must be 1..=2, `sampleRate` 1..=96000 Hz (otherwise InvalidArg). When splitting,
   * the first file (`name-001.flac`) is created immediately.
   */
  static create(path: string, sampleRate: number, channels: number, splitSeconds?: number | undefined | null): FlacEncoder
  /**
   * Append interleaved f32 (length must be a multiple of `channels`, otherwise InvalidArg).
   *
   * After writing, if the current file's frame count reaches the threshold, finalize immediately and
   * rotate to the next file (the next `writeChunk` starts the new file).
   */
  writeChunk(samples: Float32Array): void
  /**
   * Write out the remainder, finalize the header, and close the open file. Safe to call repeatedly
   * (subsequent calls are no-ops). Dropping without calling this still closes through `FlacWriter`'s
   * best-effort Drop, but call this to detect write errors.
   */
  finalize(): void
}
/**
 * Offline noise suppressor (RNNoise via nnnoiseless, embedded weights). **Requires 48kHz**;
 * intended to reduce steady noise in microphone recordings (fans, air conditioning, typing, etc.).
 *
 * Fixed latency of [`FRAME_SIZE`](flexaudio_denoise::FRAME_SIZE) (10ms at 48kHz). Output is
 * the input delayed by one frame. The first frame is silence padding;
 * retrieve the remaining trailing frame with [`Denoiser::flush`].
 */
export declare class Denoiser {
  /**
   * Construct with a channel count (1 = mono, 2 = stereo interleaved). Out-of-range values yield
   * InvalidArg.
   */
  constructor(channels: number)
  /**
   * Suppress noise in arbitrary-length interleaved f32 (±1.0 normalized, 48kHz, length a multiple of
   * channels), returning a **new array** (copied because in-place processing is awkward in napi).
   * A length not divisible by channels yields InvalidArg.
   */
  process(samples: Float32Array): Float32Array
  /**
   * Process the carried remainder, return the trailing delay (1 frame/ch), and close the stream.
   * Then return to the freshly constructed state, ready to process another stream.
   */
  flush(): Float32Array
  /** Initialize all RNN state, carryover, and delay lines. */
  reset(): void
}
